EasyProject/EasyProject/Controllers/ProgramadorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EasyProject.BusinessLogic;
using EasyProject.Exceptions;
using EasyProject.Models;
using EasyProject.Repositories;
using Newtonsoft.Json;

namespace EasyProject.Controllers
{
    public class ProgramadorController : Controller
    {
        private ProgramadorBLL ProgramadorBLL = new ProgramadorBLL();
        private EasyProjectEntities db = new EasyProjectEntities();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listar()
        {
            return View();
        }

        public JsonResult GetProgramador(long idProgramador)
        {
            try
            {
                ContentProgramador prog = ProgramadorBLL.GetProgramador(idProgramador);
                return Json(prog, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { msg = ExceptionHandler.HandleException(ex) });
            }
        }

        public JsonResult GetProgramadores()
        {
            try
            {
                List<ContentProgramador> prog = ProgramadorBLL.GetProgramadores();
                return Json(prog, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { msg = ExceptionHandler.HandleException(ex) });
            }
        }

        public JsonResult Insert(Programador programador)
        {
            try
            {
                return Json(new { retorno = ProgramadorBLL.Add(programador), msg = "OK|Registro cadastrado com sucesso" });
            }
            catch (Exception ex)
            {
                return Json(new { msg = ExceptionHandler.HandleException(ex) });
            }
        }

        [HttpPost]
        public JsonResult Update(Programador updatedProgramador)
        {
            try
            {
                ProgramadorBLL.Update(updatedProgramador);
                return Json(new { msg = "OK|Registro alterado com sucesso" });
            }
            catch (Exception ex)
            {
                return Json(new { msg = ExceptionHandler.HandleException(ex) });
            }
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            try
            {
                ProgramadorBLL.Remove(id);
                return Json(new { msg = "OK|Registro deletado com sucesso" });
            }
            catch (Exception ex)
            {
                return Json(new { msg = ExceptionHandler.HandleException(ex) });
            }
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

    }
}

EasyProject/EasyProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        @ViewBag.Title - Easy Communication & Technology
    </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body ng-app="my-easyproject">
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <div class="main-warp">
        <header class="header-section">
            <div class="header-close">
                <i class="fa fa-times"></i>
            </div>
            <div class="header-warp">
                <a href="" class="site-logo">
                    <img src="~/img/logo.png" style="margin-left:30%;" alt="">
                </a>
                <img src="~/img/menu-icon.png" alt="" class="menu-icon">
                <ul class="main-menu">
                    <li class="active">
                        @Html.ActionLink("Home", "Index", "Home")
                    </li>
                    <li>@Html.ActionLink("Trabalhe Conosco", "Index", "Programador", null, new { id = "ProgramadorIndex" })</li>
                    <li>@Html.ActionLink("Nossos Talentos", "Listar", "Programador", null, new { id = "ProgramadorLista" })</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home", null, new { id = "ProgramadorContact" })</li>
                </ul>
                <div class="social-links-warp">
                    <div class="social-links">
                        <a href=""><i class="fa fa-behance"></i></a>
                        <a href=""><i class="fa fa-dribbble"></i></a>
                        <a href=""><i class="fa fa-twitter"></i></a>
                        <a href=""><i class="fa fa-facebook"></i></a>
                        <a href=""><i class="fa fa-pinterest"></i></a>
                    </div>
                    <div class="social-text">Redes sociais</div>
                </div>
            </div>
            <div class="copyright">EASY CONTEC 2019 / TODOS OS DIREITOS RESERVADOS</div>
        </header>
        @RenderBody()
    </div>
    
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i" rel="stylesheet">
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    <script src="~/Scripts/app/app.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>